# Generated by Django 4.2.1 on 2023-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimage',
            name='public_name',
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
