# Generated by Django 4.2.1 on 2023-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('min_amount', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
