# Generated by Django 4.2.1 on 2023-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_coupon_code_cartitem_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
